name: "CI/CD for Time2Feast web application"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.4
      - name: Install dependencies
        run: bundle install
      - name: Security audit dependencies
        run: bundle exec bundler-audit --update
      - name: Security audit application code
        run: bundle exec brakeman -q  -w2
      - name: Lint Ruby files
        run: bundle exec rubocop --parallel --autocorrect --disable-uncorrectable
      - name: Lint Embedded Ruby files
        run: bundle exec erb --lint-all --autocorrect
        continue-on-error: true

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.4

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Prepare Database
        run: |
          bundle exec rails db:migrate
          bundle exec rails db:create
          bundle exec rails db:schema:load

      - name: Precompile assests
        run: bundle exec rails assets:precompile

  deploy:
    runs-on: ubuntu-latest
    # Add test to needs later
    needs: [build]
    env:
      # GitHub secrets
      PRIVATE_KEY: ${{ secrets.EC2_INSTANCE_KEY_PAIR }}
      EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      EC2_PUBLIC_DNS: ${{ secrets.EC2_PUBLIC_DNS }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Save private key and set permissions
        run: |
          echo "$PRIVATE_KEY" > private-key.pem
          chmod 600 primary-key.pem

      - name: SSH into instance
        run: |
          ssh -o StrictHostKeyChecking=no -i private-key.pem \
          ${{ env.EC2_USERNAME }}@${{ env.EC2_PUBLIC_DNS }} \
          sudo rm -rf Time2Feast; git clone https://github.com/DevOpsSec-Team-Project/Time2Feast; \
          source Time2Feast/deploy.sh
